### PR TITLE
Add eBird, update Sophie and fix some typos

### PR DESCRIPTION
**Pull request by yangsophieee**

### CODE REVIEW

**Review by dfalster — CHANGES_REQUESTED** [review]
Nice work Sophie. Alas, two unexpected issues:

1. the ebird website doesn’t let me see your profile without logging in. Is that normal? 
2.  The crow isn’t showing either. Hmm, i wonder why.

There’s a preview of changes at https://deploy-preview-10--danielfalster.netlify.app/

**Comment by yangsophieee** [comment]
My new commit should have fixed the crow! Looks like eBird doesn't allow people to look at profiles unless they are logged in according to their website.

**Comment by dfalster** [comment]
Should be `fa fa-crow` not `fas fa-crow`

**Comment by dfalster** [comment]
Ok, issue is likely the version of font awesome bing used. I have 3.1 on the website, which doesn't include the crow. Do any of these icons suits? https://fontawesome.com/v3.1/icons/

**Comment by yangsophieee** [comment]
Oh, from the original website you sent me it said fas fa-crow so I thought that was the issue. The new link you sent me gives a '404 Page not found' error. I don't mind what icon you pick!

**Pull request merged**
